### ISSUE TITLE
Does the OG Alarm Panel work with esphome too?

### ISSUE THREAD

**Issue by monsieurlatte** [konnected-io/konnected-esphome#1]
I got in when it was just a kickstarter, mine looks like an actual esp286 device that is just pushed onto a board that has all the regular hookups.  Also I have my piezo hooked up to zone 5 because there is no out on the first gen boards, so what would the yaml look like for that type?  Hoping us first gen supporters aren't left out :D

**Comment by heythisisnate** [comment]
Yes, our v1 product using the NodeMCU module works with ESPHome too. It's the same chip and firmware, no modifications necessary. Set `warning_beep_pin` to `$zone5` on line 65.
