### ISSUE TITLE
Disable status LED

### ISSUE THREAD

**Issue by jsbrich** [konnected-io/konnected-esphome#16]
With the Konnected firmware, there was an option to disable the Status LED from blinking when a zone was triggered.  Is there a way to do that with the esphome code?

**Comment by heythisisnate** [comment]
An option for this was just added in 623bb0376ee7cab8c21e3d312ab9c626dd4e859e. To disable the status LED, just add:
```
substitutions:
  blink_on_state: "false"
```

**Comment by jsbrich** [comment]
Works perfectly.  Thanks!
