### ISSUE TITLE
Make internal webserver enablement a substitution

### ISSUE THREAD

**Issue by pmuir** [konnected-io/konnected-esphome#18]
Currently, the internal webserver is hardcoded to `true`.  Once the panel is up and running disabling it is clearly necessary as it's only an http server and TLS is not supported. It would be nice if this was a substitution as then it would be very easy to disable it without editing the package.

**Comment by heythisisnate** [comment]
Unfortunately it's not possible to enable/disable the web server via a substitution or at runtime. All ESPHome components are enabled at build time, and as far as I know there's no way to conditionally enable a component.

What I recommend is to copy the contents of the product package from this repo into your YAML file in place of the reference to the package. Then add/remove sub-packages or components that you want.
