### ISSUE TITLE
Hidden SSID not working

### ISSUE THREAD

**Issue by jcbshw** [konnected-io/konnected-esphome#2]
My alarm panel was unable to connect to a hidden SSID after flashing ESPHome. Is it possible to add this feature?

Thanks!

**Comment by heythisisnate** [comment]
You would have to build the firmware yourself and include the hidden SSID wifi credentials in the firmware config. An easy way to do this is using ESPHome dashboard (via Home Assistant add-ons or running on your computer). Click _+ New Device_ then before flashing/installing edit the .yaml file and copy paste alarm-panel-espXXX.yaml from this repo but keep the `wifi` section with your stored ssid and password.
