### ISSUE TITLE
Updating from ESPHome Integration in HomeAssistant

### ISSUE THREAD

**Issue by wjwnz** [konnected-io/konnected-esphome#22]
Hi,

Each time I update using the ESPHome Integration I have to manually go and re-deploy the panel on console as it loses network access.

Latest deployment was 2023.10.6, didnt come back after reboot.

Thanks

**Comment by heythisisnate** [comment]
Related to #15 

The fix is to add the following to your adopted config (for Alarm Panel Pro v1.8 and newer):
```
substitutions:
  ethernet_type: RTL8201
```
