### ISSUE TITLE
Ethernet on Local Alarm - Alarm Panel Pro

### ISSUE THREAD

**Issue by Jeflangbeen** [konnected-io/konnected-esphome#29]
HI,

On the Local Alarm file for alarm panel pro wifi is standard, so the ethernet port of my Konnected panel (V1.7) isn't working anymore.

I would like to have it hardwired to ethernet with a  wifi failover if neccesary, i tried several things but can't get it to work.

Does anyone have the code for this?

Thanks in advance.

**Comment by heythisisnate** [comment]
Unfortunately with ESPHome it's not possible to have a WiFi failover. You can only activate the Ethernet or WiFi network adapter, but not both. To choose Ethernet just include `packages/ethernet.yaml`
