### ISSUE TITLE
Downloading firmware fails

### ISSUE THREAD

**Issue by psmith3** [konnected-io/konnected-esphome#3]
I am trying to flash a brand new Alarm Panel Pro with the ESPhome firmware at install.konnected.io/esphome and when I select the option to install the firmware, I get the following 403 error. 
`Downlading firmware https://konnected-io.s3.us-east-2.amazonaws.com/builds/esphome/konnected-esphome-alarm-panel-esp32-lan8720-.bin failed: 403`

**Comment by heythisisnate** [comment]
Thank you for letting us know. The filename looks incomplete, so there may have been an error in our automated build/release process. I will look into this.

**Comment by heythisisnate** [comment]
This is fixed now.

**Comment by psmith3** [comment]
Confirmed. All working now.
