### ISSUE TITLE
Support more than 12 zone - code for expansion kit

### ISSUE THREAD

**Issue by diogopms** [konnected-io/konnected-esphome#30]
Hi, I would like to support more than 12 zones in the case of alarm pro or more than 6 zones in case of simple alarm. Is the expansion kit compatible with esphome yaml

Thanks

**Comment by heythisisnate** [comment]
Konnected does not have an "expansion kit"

To support more zones than on a single panel, you can simply add more panels. Using Home Assistant as the brains of the alarm logic, each panel only needs to monitor and report a subset of zones to HA, which consolidates them into a single alarm system. Using this method you can also add additional sensors or outputs from non-Konnected devices.

**Comment by diogopms** [comment]
Ok thanks 👍🏻
