### ISSUE TITLE
No instructions for determining which panel you have

### ISSUE THREAD

**Issue by rayzorben** [konnected-io/konnected-esphome#31]
When I go to the website to flash it has me choose the version

![image](https://github.com/konnected-io/konnected-esphome/assets/7737834/9f709029-fffc-48ef-886e-de9408eae35a)

However I have no clue which version I am  using, and I do not see it in the Android App anywhere

Would be nice to have instructions on how to determine this.

**Comment by heythisisnate** [comment]
The version number is printed on the front of the board, underneath the logo.
