### ISSUE TITLE
Unable to connect to Alarm Panel Pro

### ISSUE THREAD

**Issue by rayzorben** [konnected-io/konnected-esphome#32]
Using v1.7 Alarm Panel Pro

I connected a USB cable to my Linux computer, and to the alarm panel, and tried flashing, but it could not find it.

I got a windows laptop and installed ALL 3 sets of drivers and tried 2 different cables, and it still could not detect the Alarm Panel Pro.

Any ideas?

**Comment by SteeledKnight** [comment]
What browser are you using?

**Comment by rayzorben** [comment]
Microsoft Edge

**Comment by SteeledKnight** [comment]
Have you tried another browser? I had issues with Firefox on Linux. Had to use Chrome

**Comment by rayzorben** [comment]
@SteeledKnight did you have to install any special drivers on linux or did it just work?

**Comment by rayzorben** [comment]
Tried Chrome too, no luck. I did a `journalctl --follow` thinking it would recognize something being plugged in but nothing is logged when I do.

The Alarm Panel Pro is powered by POE, and I am plugging into the MicroUSB port with a cable that I am certain is designed for data. 

Does it need to be plugged in with normal power and MicroUSB?

**Comment by SteeledKnight** [comment]
I know the Linux kernel ships with the needed drivers, so drivers shouldn't be needed on Linux. I hate to ask, but have you confirmed with another device that the cable carries data? I went through 5 cables before I found one with data pins connected. It might be worth connecting to DC power if you can

**Comment by rayzorben** [comment]
The website for Konnected says PoE or DC. But no, I am not sure. You know how may devices I have that still use MicroUSB for data? ZERO.

**Comment by heythisisnate** [comment]
On linux it should show up as `/dev/ttyUSB` or similar. Do you see any ports that look like that when plugged in?

**Comment by rayzorben** [comment]
> On linux it should show up as `/dev/ttyUSB` or similar. Do you see any ports that look like that when plugged in?

No. I just ordered a new cable from Amazon to make sure I have the correct data cable.
