### ISSUE TITLE
Migrations from Konnected Software

### ISSUE THREAD

**Issue by socal0001** [konnected-io/konnected-esphome#34]
I've been using using the konnected software since forever with home assistant.  I'm on Firmware
2.3.0.  Is there an easy/automated way to migrate to esphome from the konnected firmware v 2.3?

Version 2.3 stopped working recently, which is frustrating.

**Comment by techunleadit** [comment]
Hi, I'll see if I can help you...
You have to follow these steps

- Get started quickly by [flashing your Konnected device with ESPHome firmware using Konnected's web-based tool](https://install.konnected.io/esphome).
- Power on the device.
- On your computer or mobile device, connect to the device's captive portal WiFi setup network named "konnected-XXXXXX" where XXXXXX is a unique hexadecimal number. For ethernet devices, plug in the Ethernet cable and skip to step 5.
- Select your home WiFi network and enter your WiFi password in the captive portal.
- Discover the Konnected device in [Home Assistant > Settings > Devices & Services](https://my.home-assistant.io/redirect/integrations)
- (Optional) Discover the device and customize the firmware in ESPHome Dashboard ([see ESPHome add-on](https://my.home-assistant.io/redirect/supervisor_store/)).
