### ISSUE TITLE
Include the ability to set a domain for the FQDN of a Konnected board using substitutions in board yaml files

### ISSUE THREAD

**Issue by sethkor** [konnected-io/konnected-esphome#6]
As a Konnected.io customer
I want to be able to set a custom domain name
So that I can address my board with a Fully Qualified Domain Name using a substitution in the panel yaml file

I have a split horizon dns, and use my domain name at home rather than .local.  I hacked around and read a bit about ESPHome to understand how to get the domain name in the ethernet.yaml file.  I think it would be useful to add this example for other users.

**Comment by heythisisnate** [comment]
I think the `domain` variable under the `ethernet:` component is what you want:
https://esphome.io/components/ethernet.html?highlight=domain
