### ISSUE TITLE
 Only one instance of the esphome ota platform is allowed per port. Note that this error may result from OTA specified in packages.

### ISSUE THREAD

**Issue by socal0001** [konnected-io/konnected-esphome#66]
My config uses:

# Enable OTA updates, with password
ota:
  - platform: esphome
    password: !secret ota_password

Given https://github.com/esphome/esphome/pull/6984 I am no longer able to update.  

Had the same problem with another component and they added an ID, so I could do the following to solve.  Can you do this too?  Maybe there should be a common ID to easily extend?

ota:
  - id: !extend ratgdo_ota
    password: "...."

**Comment by drothenberger** [comment]
The main branch now sets the ID to "konnected_ota", so you can extend it.
